# Generated by Django 3.0.5 on 2021-12-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211230_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to=''),
        ),
    ]
