# Generated by Django 3.0.5 on 2021-12-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(default='')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_material', models.URLField(blank=True, null=True)),
                ('past_Question', models.URLField(blank=True, null=True)),
                ('video_refence', models.URLField(blank=True, null=True)),
                ('Useful_link', models.URLField(blank=True, null=True)),
                ('General_assessment', models.URLField(blank=True, null=True)),
                ('Topic_assessment', models.URLField(blank=True, null=True)),
                ('Other_material', models.URLField(blank=True, null=True)),
                ('Old_material', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study.StudyCourse')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Level')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semest', to='Study.SemesterCategory')),
            ],
        ),
    ]
