# Generated by Django 3.0.5 on 2021-12-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accommodationcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Categoryshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ordring', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCountdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=225)),
                ('when', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_title', models.CharField(max_length=225)),
                ('information_description', models.TextField()),
                ('information_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10, unique=True)),
                ('article', models.CharField(max_length=50)),
                ('article2', models.CharField(max_length=50)),
                ('article3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=100)),
                ('video', models.TextField(blank=True, null=True)),
                ('pdf', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Level')),
            ],
        ),
        migrations.CreateModel(
            name='ShopIteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField()),
                ('discount_price', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=225)),
                ('Active', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='')),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('picture2', models.FileField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='index.Categoryshop')),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('Title', models.CharField(max_length=225)),
                ('Authors', models.CharField(max_length=225)),
                ('body', models.TextField()),
                ('Description', models.TextField()),
                ('Date_post', models.DateTimeField()),
                ('tage', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='index.Category')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Level'),
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostel', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=225, null=True)),
                ('price', models.FloatField()),
                ('discount_price', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=225)),
                ('Active', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='')),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('picture2', models.FileField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accomo', to='index.accommodationcategory')),
            ],
        ),
    ]
