# Generated by Django 3.0.5 on 2021-12-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
    ]
