# Generated by Django 3.0.5 on 2021-12-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_tutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
